POST http://localhost:3000/api/users/login?name=contoh
Content-Type: application/json

{
  "username": "a",
  "password": "a"
}

###
GET http://localhost:3000/api/users/current
x-username: 2

###
POST http://localhost:3000/orders
Content-Type: application/json

{
  "email": "adityaric72@gmail.com",
  "total": 10000000
}
